name: Run markdown lint
on:
  push
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: CI
          run: |
            npm install remark-cli remark-preset-lint-consistent
            npx remark . --use remark-preset-lint-consistent --frail
